---
- name: create a user using a variable
  hosts: all
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }} on host {{ ansible_hostname }} 
      ansible.builtin.debug:
        msg: "{{ user }}"