- name: "mariadb-server installation" 
  package: 
    name:  "mariadb-server,python3-PyMySQL" 
    state: "installed" 
 
- name: "start mariadb service" 
  service: 
    name:  "mariadb" 
    state: "started" 
    enabled: yes
